import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  members: [
    {
      id: 1,
      username: "horebBarriga",
      email: "hor.barr1ga@gmail.com",
      image: "",
      rolesID: ["1"],
      viewing: "Cards",
      status: "online",
    },
    {
      id: 2,
      username: "DainSiao",
      email: "dainalou@gmail.com",
      rolesID: ["2", "2", "5"],
      image: "",
      viewing: "",
      status: "offline",
    },
    {
      id: 2,
      username: "DainSiao",
      email: "dainalou@gmail.com",
      rolesID: ["2"],
      image: "",
      viewing: "",
      status: "offline",
    },
    {
      id: 2,
      username: "DainSiao",
      email: "dainalou@gmail.com",
      rolesID: ["3", "2", "5", "3", "6", "4", "7", "8"],
      image: "",
      viewing: "",
      status: "offline",
    },
    {
      id: 3,
      username: "CJCaburnay",
      email: "caburnaycj@gmail.com",
      rolesID: ["3", "2", "5"],
      image: "",
      viewing: "",
      status: "offline",
    },
    {
      id: 4,
      username: "Bryll",
      email: "bryllandales@gmail.com",
      rolesID: ["2"],
      image: "",
      viewing: "Identifications",
      status: "idle",
    },
    {
      id: 5,
      username: "JemseyAmonsot",
      email: "jemseyamonsot@gmail.com",
      rolesID: ["2"],
      image: "",
      viewing: "Secure Notes",
      status: "online",
    },
    {
      id: 6,
      username: "Nicholai",
      email: "jemseyamonsot@gmail.com",
      rolesID: ["2"],
      image: "",
      viewing: "Logins",
      status: "online",
    },
    {
      id: 7,
      username: "VanguardiaAJ",
      email: "jemseyamonsot@gmail.com",
      rolesID: ["2"],
      image: "",
      viewing: "Cards",
      status: "online",
    },
    {
      id: 8,
      username: "Teddyzb",
      email: "jemseyamonsot@gmail.com",
      rolesID: ["2"],
      image: "",
      viewing: "Logins",
      status: "online",
    },
    {
      id: 9,
      username: "Luke",
      email: "jemseyamonsot@gmail.com",
      rolesID: ["2"],
      image: "",
      viewing: "Logins",
      status: "online",
    },
  ],
  memberLoading: false,
  memberFulfilled: false,
  memberError: false,
  memberMessage: "",
};

const memberSlice = createSlice({
  name: "member",
  initialState,
  reducers: {
    resetMembers: (state) => initialState,
  },
});

export const { resetMembers } = memberSlice.actions;
export default memberSlice.reducer;
