import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  members: [
    {
      id: 1,
      username: "horebBarriga",
      email: "hor.barr1ga@gmail.com",
      image: "",
      role: "vaultOwner",
      viewing: "Cards",
      status: "online",
    },
    {
      id: 2,
      username: "DainSiao",
      email: "dainalou@gmail.com",
      role: "family",
      image: "",
      viewing: "",
      status: "offline",
    },
    {
      id: 2,
      username: "DainSiao",
      email: "dainalou@gmail.com",
      role: "family",
      image: "",
      viewing: "",
      status: "offline",
    },
    {
      id: 2,
      username: "DainSiao",
      email: "dainalou@gmail.com",
      role: "employee",
      image: "",
      viewing: "",
      status: "offline",
    },
    {
      id: 3,
      username: "CJCaburnay",
      email: "caburnaycj@gmail.com",
      role: "employee",
      image: "",
      viewing: "",
      status: "offline",
    },
    {
      id: 4,
      username: "Bryll",
      email: "bryllandales@gmail.com",
      role: "family",
      image: "",
      viewing: "Identifications",
      status: "idle",
    },
    {
      id: 5,
      username: "JemseyAmonsot",
      email: "jemseyamonsot@gmail.com",
      role: "family",
      image: "",
      viewing: "Secure Notes",
      status: "online",
    },
    {
      id: 6,
      username: "Nicholai",
      email: "jemseyamonsot@gmail.com",
      role: "family",
      image: "",
      viewing: "Logins",
      status: "online",
    },
    {
      id: 7,
      username: "VanguardiaAJ",
      email: "jemseyamonsot@gmail.com",
      role: "family",
      image: "",
      viewing: "Cards",
      status: "online",
    },
    {
      id: 8,
      username: "Teddyzb",
      email: "jemseyamonsot@gmail.com",
      role: "family",
      image: "",
      viewing: "Logins",
      status: "online",
    },
    {
      id: 9,
      username: "Luke",
      email: "jemseyamonsot@gmail.com",
      role: "family",
      image: "",
      viewing: "Logins",
      status: "online",
    },
  ],
  memberLoading: false,
  memberFulfilled: false,
  memberError: false,
  memberMessage: "",
};

const memberSlice = createSlice({
  name: "member",
  initialState,
  reducers: {
    resetMembers: (state) => initialState,
  },
});

export const { resetMembers } = memberSlice.actions;
export default memberSlice.reducer;
